# Generated by Django 4.2.2 on 2023-06-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_presenca_datapresenca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='NomeAluno',
            field=models.CharField(max_length=100, verbose_name='Nome_do_Aluno'),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='NomeCurso',
            field=models.CharField(max_length=20, verbose_name='Nome_do_Curso'),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='NomeProfessor',
            field=models.IntegerField(verbose_name='Nome_do_Professor'),
        ),
    ]
